[package]
name = "feoxide"
version = "0.1.0"
authors = ["Shafik Amin <shafik23@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

[[bin]]
name = "feoxide"
path = "src/main.rs"
